import {
  Brush, Sparkles, Building2, Car, Plane, Heart, Briefcase, Home, FlaskConical,
  Film, Landmark, Bitcoin, Theater, Palette, Scale, LineChart, GraduationCap,
  Rocket, Wrench, Trophy, BookOpen, DollarSign, Dumbbell, Camera, Gamepad2,
  UtensilsCrossed, Hourglass, Smile, Languages, Brain, TrendingUp, Newspaper,
  Baby, PawPrint, Vote, Zap, Code2, Stethoscope, Leaf, Shirt, Bike, Music,
  TreePine, Building, Briefcase as BriefcaseIcon, BookMarked, Globe, Cpu,
  Smartphone, Tv, ShoppingBag, MapPin, HeartHandshake, Church, ShieldCheck,
  Sun, GitBranch, Atom,
} from "lucide-react";
import type { LucideIcon } from "lucide-react";

export type Category = { value: string; label: string; icon: LucideIcon };

// Alphabetical (PT-BR) — broad coverage, Reddit-style.
export const CATEGORIES: Category[] = [
  { value: "animais", label: "Animais", icon: PawPrint },
  { value: "anime", label: "Anime & Mangá", icon: Tv },
  { value: "arquitetura", label: "Arquitetura", icon: Building2 },
  { value: "arte", label: "Arte", icon: Brush },
  { value: "astronomia", label: "Astronomia", icon: Atom },
  { value: "automoveis", label: "Automóveis", icon: Car },
  { value: "aviacao", label: "Aviação", icon: Plane },
  { value: "beleza", label: "Beleza", icon: Sparkles },
  { value: "carreira", label: "Carreira", icon: Briefcase },
  { value: "casa", label: "Casa & Decoração", icon: Home },
  { value: "ciencia", label: "Ciência", icon: FlaskConical },
  { value: "cinema", label: "Cinema & TV", icon: Film },
  { value: "concursos", label: "Concursos Públicos", icon: Landmark },
  { value: "criptomoedas", label: "Criptomoedas", icon: Bitcoin },
  { value: "cultura", label: "Cultura", icon: Theater },
  { value: "design", label: "Design", icon: Palette },
  { value: "direito", label: "Direito", icon: Scale },
  { value: "economia", label: "Economia", icon: LineChart },
  { value: "educacao", label: "Educação", icon: GraduationCap },
  { value: "empreendedorismo", label: "Empreendedorismo", icon: Rocket },
  { value: "engenharia", label: "Engenharia", icon: Wrench },
  { value: "esportes", label: "Esportes", icon: Trophy },
  { value: "filosofia", label: "Filosofia", icon: BookOpen },
  { value: "financas", label: "Finanças", icon: DollarSign },
  { value: "fitness", label: "Fitness", icon: Dumbbell },
  { value: "fotografia", label: "Fotografia", icon: Camera },
  { value: "games", label: "Games", icon: Gamepad2 },
  { value: "gastronomia", label: "Gastronomia", icon: UtensilsCrossed },
  { value: "historia", label: "História", icon: Hourglass },
  { value: "humor", label: "Humor", icon: Smile },
  { value: "idiomas", label: "Idiomas", icon: Languages },
  { value: "ia", label: "Inteligência Artificial", icon: Brain },
  { value: "investimentos", label: "Investimentos", icon: TrendingUp },
  { value: "jornalismo", label: "Jornalismo", icon: Newspaper },
  { value: "leitura", label: "Leitura & Livros", icon: BookMarked },
  { value: "marketing", label: "Marketing", icon: Zap },
  { value: "medicina", label: "Medicina & Saúde", icon: Stethoscope },
  { value: "meio-ambiente", label: "Meio Ambiente", icon: Leaf },
  { value: "moda", label: "Moda", icon: Shirt },
  { value: "motociclismo", label: "Motociclismo", icon: Bike },
  { value: "musica", label: "Música", icon: Music },
  { value: "natureza", label: "Natureza", icon: TreePine },
  { value: "negocios", label: "Negócios", icon: Building },
  { value: "noticias", label: "Notícias", icon: Newspaper },
  { value: "pais-filhos", label: "Pais & Filhos", icon: Baby },
  { value: "pets", label: "Pets", icon: PawPrint },
  { value: "politica", label: "Política", icon: Vote },
  { value: "produtividade", label: "Produtividade", icon: GitBranch },
  { value: "programacao", label: "Programação", icon: Code2 },
  { value: "psicologia", label: "Psicologia", icon: Brain },
  { value: "relacionamentos", label: "Relacionamentos", icon: HeartHandshake },
  { value: "religiao", label: "Religião & Espiritualidade", icon: Church },
  { value: "saude", label: "Saúde", icon: Heart },
  { value: "seguranca", label: "Segurança", icon: ShieldCheck },
  { value: "startups", label: "Startups", icon: Rocket },
  { value: "sustentabilidade", label: "Sustentabilidade", icon: Sun },
  { value: "tecnologia", label: "Tecnologia", icon: Cpu },
  { value: "trabalho-remoto", label: "Trabalho Remoto", icon: Smartphone },
  { value: "turismo", label: "Turismo", icon: MapPin },
  { value: "viagens", label: "Viagens", icon: Globe },
  { value: "compras", label: "Compras & Varejo", icon: ShoppingBag },
];
