/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TopRouteImport } from './routes/top'
import { Route as RecentesRouteImport } from './routes/recentes'
import { Route as PopularRouteImport } from './routes/popular'
import { Route as PerfilRouteImport } from './routes/perfil'
import { Route as NoticiasRouteImport } from './routes/noticias'
import { Route as ExplorarRouteImport } from './routes/explorar'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ThreadIdRouteImport } from './routes/thread.$id'
import { Route as GSlugRouteImport } from './routes/g.$slug'

const TopRoute = TopRouteImport.update({
  id: '/top',
  path: '/top',
  getParentRoute: () => rootRouteImport,
} as any)
const RecentesRoute = RecentesRouteImport.update({
  id: '/recentes',
  path: '/recentes',
  getParentRoute: () => rootRouteImport,
} as any)
const PopularRoute = PopularRouteImport.update({
  id: '/popular',
  path: '/popular',
  getParentRoute: () => rootRouteImport,
} as any)
const PerfilRoute = PerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => rootRouteImport,
} as any)
const NoticiasRoute = NoticiasRouteImport.update({
  id: '/noticias',
  path: '/noticias',
  getParentRoute: () => rootRouteImport,
} as any)
const ExplorarRoute = ExplorarRouteImport.update({
  id: '/explorar',
  path: '/explorar',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ThreadIdRoute = ThreadIdRouteImport.update({
  id: '/thread/$id',
  path: '/thread/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const GSlugRoute = GSlugRouteImport.update({
  id: '/g/$slug',
  path: '/g/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/explorar': typeof ExplorarRoute
  '/noticias': typeof NoticiasRoute
  '/perfil': typeof PerfilRoute
  '/popular': typeof PopularRoute
  '/recentes': typeof RecentesRoute
  '/top': typeof TopRoute
  '/g/$slug': typeof GSlugRoute
  '/thread/$id': typeof ThreadIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/explorar': typeof ExplorarRoute
  '/noticias': typeof NoticiasRoute
  '/perfil': typeof PerfilRoute
  '/popular': typeof PopularRoute
  '/recentes': typeof RecentesRoute
  '/top': typeof TopRoute
  '/g/$slug': typeof GSlugRoute
  '/thread/$id': typeof ThreadIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/explorar': typeof ExplorarRoute
  '/noticias': typeof NoticiasRoute
  '/perfil': typeof PerfilRoute
  '/popular': typeof PopularRoute
  '/recentes': typeof RecentesRoute
  '/top': typeof TopRoute
  '/g/$slug': typeof GSlugRoute
  '/thread/$id': typeof ThreadIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/explorar'
    | '/noticias'
    | '/perfil'
    | '/popular'
    | '/recentes'
    | '/top'
    | '/g/$slug'
    | '/thread/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/explorar'
    | '/noticias'
    | '/perfil'
    | '/popular'
    | '/recentes'
    | '/top'
    | '/g/$slug'
    | '/thread/$id'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/explorar'
    | '/noticias'
    | '/perfil'
    | '/popular'
    | '/recentes'
    | '/top'
    | '/g/$slug'
    | '/thread/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  ExplorarRoute: typeof ExplorarRoute
  NoticiasRoute: typeof NoticiasRoute
  PerfilRoute: typeof PerfilRoute
  PopularRoute: typeof PopularRoute
  RecentesRoute: typeof RecentesRoute
  TopRoute: typeof TopRoute
  GSlugRoute: typeof GSlugRoute
  ThreadIdRoute: typeof ThreadIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/top': {
      id: '/top'
      path: '/top'
      fullPath: '/top'
      preLoaderRoute: typeof TopRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recentes': {
      id: '/recentes'
      path: '/recentes'
      fullPath: '/recentes'
      preLoaderRoute: typeof RecentesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/popular': {
      id: '/popular'
      path: '/popular'
      fullPath: '/popular'
      preLoaderRoute: typeof PopularRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/perfil': {
      id: '/perfil'
      path: '/perfil'
      fullPath: '/perfil'
      preLoaderRoute: typeof PerfilRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/noticias': {
      id: '/noticias'
      path: '/noticias'
      fullPath: '/noticias'
      preLoaderRoute: typeof NoticiasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/explorar': {
      id: '/explorar'
      path: '/explorar'
      fullPath: '/explorar'
      preLoaderRoute: typeof ExplorarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/thread/$id': {
      id: '/thread/$id'
      path: '/thread/$id'
      fullPath: '/thread/$id'
      preLoaderRoute: typeof ThreadIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/g/$slug': {
      id: '/g/$slug'
      path: '/g/$slug'
      fullPath: '/g/$slug'
      preLoaderRoute: typeof GSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  ExplorarRoute: ExplorarRoute,
  NoticiasRoute: NoticiasRoute,
  PerfilRoute: PerfilRoute,
  PopularRoute: PopularRoute,
  RecentesRoute: RecentesRoute,
  TopRoute: TopRoute,
  GSlugRoute: GSlugRoute,
  ThreadIdRoute: ThreadIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
